apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: v1
  name: nginx-named-port
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    application: v1
status:
  loadBalancer: {}
