apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: flask-ing
spec:
  ingressClassName: nginx
  rules:
  - host: k.ravshandev.uz
    http:
      paths:
      - backend:
          service:
            name: flaskapp
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
